---
- name: Install and enable docker service
  hosts: servers
  become: yes
  tasks:
    - name: Install docker
      apt:
        name: docker.io
        state: latest

    - name: Enable docker
      service:
        name: docker
        state: started
        enabled: yes
